### ISSUE TITLE
pipeline.run_recipe returns duplicate files

### ISSUE THREAD

**Issue by semaphoreP** [geminiplanetimager/gpipy#2]
If there are multiple "Save" steps in a recipe, the filenames outputted by pipeline.run_recipe will contain duplicates. 

Reproduce: I just ran the test scripts for the GPI DRP and assert len(outfiles)==nfiles_expected failed on the pol recipe because there are two save steps for the podc cubes (e.g. 'S20140422S0281_podc.fits' is included twice in the outputted filenames). 

I think duplicate filenames should be removed before outputting. Does that sound reasonable?

**Comment by mperrin** [comment]
Ah, whoops, I ran into and fixed this bug just a couple weeks ago. Looks like I never pushed changes to github though. My bad.

**Comment by mperrin** [comment]
Fix in https://github.com/geminiplanetimager/gpipy/commit/8bb89fbd5f2c620d9f04a79f1d23e1d48f9ccb96 now pushed to github, so try that?

**Comment by mperrin** [comment]
Ha, I like that we made precisely identical fixes for this one, apart from comment text :-)
